theme: jekyll-theme-slate
show_downloads: true
title: Jekyll Theme Collection
preview_path: https://www.gem-editor.com/gwc/theme
website_theme:
  - name: 1at
    desc: Vertical Button, affix
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2
    desc: Navigation Bar
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2fi
    desc: Navigation Bar, fixed top
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2in
    desc: Navigation Bar, inverted
    cssf: Bootstrap 3
    pwfn: 501
  - name: 2if
    desc: Navigation Bar, inverted, fixed top
    cssf: Bootstrap 3
    pwfn: 501
